import { defineConfig } from 'vite'
import { spawn } from 'node:child_process'
import path from 'node:path'

// The HTML entry points are generated by scripts/prepare.mjs from the data and locale files.
// In dev, editing any of those regenerates the pages and reloads the browser.
function regeneratePages() {
  let running = null
  const watched = /[\\/]src[\\/](data|locales|render)[\\/]/
  return {
    name: 'gracias-regenerate-pages',
    apply: 'serve',
    handleHotUpdate({ file, server }) {
      if (!watched.test(file) || file.includes(`${path.sep}generated${path.sep}`)) return
      if (running) return []
      running = spawn(process.execPath, ['scripts/prepare.mjs', '--pages-only'], { stdio: 'inherit' })
      running.on('exit', () => {
        running = null
        server.ws.send({ type: 'full-reload' })
      })
      return []
    },
  }
}

export default defineConfig({
  appType: 'mpa',
  plugins: [regeneratePages()],
  build: {
    rollupOptions: {
      input: {
        landing: 'index.html',
        es: 'es/index.html',
        en: 'en/index.html',
        'es-archivo': 'es/archivo/index.html',
        'en-archive': 'en/archive/index.html',
        'es-cinematic': 'es/cinematic/index.html',
        'en-cinematic': 'en/cinematic/index.html',
        original: 'original/index.html',
        cinematic: 'cinematic/index.html',
      },
    },
  },
})
